@startuml state
    
    [*] --> Initialization
    Initialization --> Pre_Operational
    Pre_Operational --> Operational: Command: Operational
    Operational --> Pre_Operational: Command: Pre_Operational
    Operational --> Initialization: Command: Reset
    Operational --> Stopped: Fault Detected
    Pre_Operational --> Key_Input: Select Mode
    Key_Input --> Pre_Operational: Mode Selected
    

    state Initialization {
        state "Init" as Initialization
        Initialization: State: Initialization
    }
    state Operational {
        state "Operational" as Operational
        Operational: State: Operational
        Operational: Task: Led On
    }

    state Pre_Operational {
        state "Pre_Operational" as Pre_Operational
        Pre_Operational: State: Pre_Operational
        Pre_Operational: Task: Blink LED 1 Hz
    }

    state Stopped {
        state "Stopped" as Stopped
        Stopped: State: Stopped
        Stopped: Task: Led Off
    }

    state Key_Input {
        state "Key_Input" as Key_Input
        Key_Input: State: Key_Input
        Key_Input: Task: Read Key
    }

@enduml
